# =============================================================================
# 共通パラメータ（base.yaml）
# =============================================================================
# このファイルは「図の見た目」「データの扱い方」「観測地点の情報」など、
# 佐波川の全年度で共通して使う設定をまとめたものです。
# 年別のファイル（sabagawa-2022.yaml など）は、この base と自動でマージされ、
# 各年度の期間（period）だけが上書きされて使われます。
# =============================================================================

# -----------------------------------------------------------------------------
# figure: グラフ・図の見た目を決める設定
# -----------------------------------------------------------------------------
# 出力される PNG のサイズ、解像度、文字の大きさ、線の太さなどを指定します。
figure:
  # graph_size_ratio: 図の「縦横比」を数値で指定。[幅の比, 高さの比] の順。
  #   例: [15, 4] は「幅15 : 高さ4」の比率。inch ではなく比だけなので、実際の大きさは base_width で決まります。
  graph_size_ratio: [15, 4]
  # base_width: 図の「幅」をインチ [inch] で指定。高さは graph_size_ratio から自動計算されます。
  #   例: base_width=9.0, ratio=[15,4] → 幅9inch, 高さ 9×(4/15)=2.4inch
  base_width: 18.0
  # dpi: 画像の解像度（ドット/インチ）。大きいほどきれいだがファイルサイズも増えます。印刷なら 150〜300 程度。
  dpi: 100
  # linewidth: グラフの線の太さ。数値が大きいほど太い線になります。
  linewidth: 1.5
  # font: 凡例・軸・タイトルごとのフォントサイズ [pt]。未指定の項目は size の値が使われます。
  font:
    size: 12           # デフォルト（他で未指定のときに使う）
    legend: 11         # 凡例の文字サイズ
    axis_label: 12     # 軸ラベル（xlabel / ylabel）の文字サイズ
    tick: 10           # 軸の目盛りラベル（数値）の文字サイズ
    title: 14          # 各サブプロットのタイトルの文字サイズ

# -----------------------------------------------------------------------------
# run_params: ノートブック実行時の動作を決める設定
# -----------------------------------------------------------------------------
run_params:
  # config_files: ノートブック側で指定。ここでは未指定＝全ケース（全年度）をまとめて処理。
  #   特定年度だけにしたい場合はノートブックで ["sabagawa-2022.yaml"] のように指定可能。
  interactive_delete: false   # true にすると、重複データ削除の前に「削除してよいか」を毎回聞かれます。自動実行時は false 推奨。
  use_cached_artifacts: false # true: 前回計算した中間データ（artifacts）を読み、図だけ描き直します。試行錯誤が速くなります。

# -----------------------------------------------------------------------------
# filter_params: 堤体内水位データにかける「フィルタ」の設定
# -----------------------------------------------------------------------------
# ノイズを減らしてグラフを見やすくするためのオプションです。OFF のときは生データをそのまま描画します。
filter_params:
  use_median_filter: false    # true にすると、堤体内水位にメディアンフィルタをかけます（ spike 除去などに有効）。
  median_window: 5            # メディアンフィルタの窓幅。奇数が望ましい（例: 5 なら前後2点ずつ含めた5点の中央値）。
  use_sg_filter: false        # true にすると、Savitzky–Golay フィルタをかけます（滑らかにしつつ形を保ちたいときに使う）。scipy が必要。
  sg_window: 11               # SG フィルタの窓幅。奇数で、sg_poly より大きくします。
  sg_poly: 3                  # SG フィルタの多項式の次数。
  save_both_filter_figures: false  # フィルタ ON のとき、適用前と適用後の図を両方保存するか。比較用。

# -----------------------------------------------------------------------------
# paths: データやコードの「フォルダの場所」を指定
# -----------------------------------------------------------------------------
# 相対パスは、ノート実行時のカレントディレクトリ（ローカルならプロジェクト直下、Colab なら waterlevel_analysis など）基準です。
paths:
  base_dir: "./"                      # 実行時の基準ディレクトリ。通常は "./" のままでよい。
  data_folder: "./data/sabagawa"     # 河川水位・降雨・堤体内水位の元データが入っているフォルダ。
  output_dir: "./output"              # 図・表・ログの出力先。中にケースごとのフォルダ（例: sabagawa-2022）ができます。
  module_path: "./src"                # 図化用の Python コード（モジュール）が入っているフォルダ。

# -----------------------------------------------------------------------------
# obs_params: どの観測データをグラフに出すか（ON/OFF）
# -----------------------------------------------------------------------------
# 1=表示する、0=表示しない。河川水位・降雨・堤体内水位を個別に切り替えられます。
obs_params:
  RWL: 1   # River Water Level: 河川水位
  RF: 1    # RainFall: 降雨
  GWL: 1   # Ground Water Level (堤体内): 堤体内水位

# -----------------------------------------------------------------------------
# graph_params: グラフの縦軸の範囲（Y軸の最小・最大値）
# -----------------------------------------------------------------------------
# 水位・降雨のグラフで、縦軸をどの範囲で表示するかを指定します。null にすると自動で決まります。
graph_params:
  miny: 10    # 水位グラフの縦軸の最小値 [m]
  maxy: 17    # 水位グラフの縦軸の最大値 [m]
  rain_miny: 0   # 降雨グラフの縦軸の最小値 [mm]。null なら自動。
  rain_maxy: 50  # 降雨グラフの縦軸の最大値 [mm]。null なら自動。

# -----------------------------------------------------------------------------
# rwl_params: 河川水位の観測地点・零点補正に関する設定
# -----------------------------------------------------------------------------
rwl_params:
  point: ["7.8k", "8.0k"]     # 表示する観測点名（キロポスト表記）。データファイルの対応する列と一致させます。
  obs_elev: 20.404            # 観測の零点高 [m]。水位値にこの高さを足して表示します。
  slide: [-9.34, -8.88]       # 各観測点ごとの補正値 [m]。obs_elev に加算して、表示用の水位を計算します。

# -----------------------------------------------------------------------------
# gwl_params: 堤体内水位（地下水水位）の観測点・センサー情報
# -----------------------------------------------------------------------------
# OYO の堤体内水位計の「部位名」と「センサー番号」「高さ」を対応させます。
gwl_params:
  parts:   # グラフに出す部位の名前のリスト。データの列名や凡例と対応します。
    - "7.8k front"
    - "7.8k shoulder"
    - "7.8k slope"
    - "7.8k toe"
    - "8.0k front"
    - "8.0k shoulder"
    - "8.0k slope"
    - "8.0k toe"
    - "balo"
    - "8.0k shoulder"
  SNs: [4855566, 4856964, 4856965, 4856970, 4856968, 4856966, 4856967, 4856969, 4857561, 4860639]  # 各部位に対応するセンサー番号（Serial Number）
  gw_elevs: [12.258, 12.283, 12.248, 12.427, 12.867, 12.813, 12.824, 12.904, 0.0, 0.0]  # 各センサーの設置高さ [m]。0 は未使用など。
  ND: null  # 必要に応じて指定する追加パラメータ。未使用のときは null。
